version: "3.9"

services:
  front:
    build: front/.
    volumes:
      - ./front/src:/app/src
    ports:
      - 3000:3000
  web:
    build: api/.
    working_dir: /usr/src/app
    command: >
      bash -c "
        ./wait-for-postgres.sh db &&
        (git clone https://github.com/rlopez0689/fullstack-interview-test.git /usr/src/repo/fullstack-interview-test  || true) &&
        python manage.py migrate && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./api:/usr/src/app/
      - ./repo:/usr/src/repo
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=mygit
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REPO_PATH=/usr/src/repo/fullstack-interview-test
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=mygit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
