# Generated by Django 4.0.1 on 2022-01-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitelements', '0003_alter_pr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel ornare mi, sed rutrum eros.'),
            preserve_default=False,
        ),
    ]
